const COL_DEF_CONSTANTS = {
  activity_date: { type: 'formattedDate', minWidth: 160 },
  actual_pmt_amt: { type: 'currency' },
  amt_past_due: { type: 'currency' },
  credit_limit: { type: 'currency' },
  current_bal: { type: 'currency' },
  date_open: { type: 'formattedDate', minWidth: 100 },
  date_closed: { type: 'formattedDate', minWidth: 110 },
  doai: { type: 'formattedDate', minWidth: 155 },
  dofd: { type: 'formattedDate', minWidth: 100 },
  dolp: { type: 'formattedDate', minWidth: 120 },
  hcola: { type: 'currency' },
  php: { minWidth: 265 },
  php1: { minWidth: 220 },
  orig_chg_off_amt: { type: 'currency' },
  smpa: { type: 'currency', minWidth: 140 },
  account_holder__cons_info_ind: { minWidth: 265 },
  account_holder__cons_info_ind_assoc: { minWidth: 265 },
  previous_values__account_holder__cons_info_ind: { minWidth: 265 },
  previous_values__account_holder__cons_info_ind_assoc: { minWidth: 265 },
  account_holder__ecoa: { minWidth: 230 },
  previous_values__account_holder__ecoa: { minWidth: 230 },
  account_holder__ecoa_assoc: { minWidth: 230 },
  k2__purch_sold_ind: { minWidth: 250 },
  k2__purch_sold_name: { minWidth: 210 },
  k4__balloon_pmt_amt: { type: 'currency' },
  l1__change_ind: { minWidth: 200 },
  l1__new_acc_num: { minWidth: 200 },
  l1__new_id_num: { minWidth: 200 },
  previous_values__l1__change_ind: { minWidth: 200 },
  previous_values__l1__new_acc_num: { minWidth: 200 },
  previous_values__l1__new_id_num: { minWidth: 200 },
  previous_values__activity_date: { type: 'formattedDate', minWidth: 160 },
  previous_values__date_open: { type: 'formattedDate', minWidth: 100 },
  previous_values__dofd: { type: 'formattedDate', minWidth: 100 },
  previous_values__date_closed: { type: 'formattedDate', minWidth: 110 },
  previous_values__current_bal: { type: 'currency' },
  previous_values__orig_chg_off_amt: { type: 'currency' }
}

export default COL_DEF_CONSTANTS
