// M2 fields that can be displayed for an account record
export default interface AccountRecord {
  activity_date?: string | null
  id_num?: string | null
  cons_acct_num?: string | null
  port_type?: string | null
  acct_type?: string | null
  date_open?: string | null
  credit_limit?: number | null
  hcola?: number | null
  terms_dur?: string | null
  terms_freq?: string | null
  smpa?: number | null
  actual_pmt_amt?: number | null
  acct_stat?: string | null
  pmt_rating?: string | null
  php?: string | null
  php1?: string | null
  spc_com_cd?: string | null
  compl_cond_cd?: string | null
  current_bal?: number | null
  amt_past_due?: number | null
  orig_chg_off_amt?: number | null
  doai?: string | null
  dofd?: string | null
  date_closed?: string | null
  dolp?: string | null
  account_holder__cons_info_ind?: string | null
  account_holder__ecoa?: string | null
  account_holder__cons_info_ind_assoc?: string[] | null
  account_holder__ecoa_assoc?: [] | null
  k2__purch_sold_ind?: string | null
  k2__purch_sold_name?: string | null
  k4__balloon_pmt_amt?: string | null
  l1__change_ind?: string | null
  l1__new_acc_num?: string | null
  l1__new_id_num?: string | null
  previous_values__account_holder__cons_info_ind?: string | null
  previous_values__account_holder__cons_info_ind_assoc?: [] | null
  previous_values__account_holder__ecoa?: string | null
  previous_values__account_holder__first_name?: string | null
  previous_values__account_holder__surname?: string | null
  previous_values__l1__change_ind?: string | null
  previous_values__l1__new_acc_num?: string | null
  previous_values__l1__new_id_num?: string | null
  previous_values__activity_date?: string | null
  previous_values__port_type?: string | null
  previous_values__acct_type?: string | null
  previous_values__date_open?: string | null
  previous_values__acct_stat?: string | null
  previous_values__pmt_rating?: string | null
  previous_values__current_bal?: number | null
  previous_values__orig_chg_off_amt?: number | null
  previous_values__dofd?: string | null
  previous_values__date_closed?: string | null
  previous_values__id_num?: string | null
}
