# Generated by Django 4.2.5 on 2023-12-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('cons_acct_num', models.CharField(max_length=200)),
                ('port_type', models.CharField(max_length=200)),
                ('acct_type', models.CharField(max_length=200)),
                ('date_open', models.DateField()),
                ('credit_limit', models.IntegerField()),
                ('hcola', models.IntegerField()),
                ('terms_dur', models.CharField(max_length=200)),
                ('terms_freq', models.CharField(max_length=200)),
                ('smpa', models.IntegerField()),
                ('actual_pmt_amt', models.IntegerField()),
                ('acct_stat', models.CharField(max_length=200)),
                ('pmt_rating', models.CharField(max_length=200)),
                ('php', models.CharField(max_length=200)),
                ('spc_com_cd', models.CharField(max_length=200)),
                ('compl_cond_cd', models.CharField(max_length=200)),
                ('current_bal', models.IntegerField()),
                ('amt_past_due', models.IntegerField()),
                ('orig_chg_off_amt', models.IntegerField()),
                ('doai', models.DateField()),
                ('dofd', models.DateField(null=True)),
                ('date_closed', models.DateField(null=True)),
                ('dolp', models.DateField(null=True)),
                ('int_type_ind', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='M2DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metro2Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UnparseableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unparseable_line', models.CharField(max_length=2000)),
                ('error_description', models.CharField(max_length=200)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.m2datafile')),
            ],
        ),
        migrations.CreateModel(
            name='N1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=200)),
                ('employer_addr1', models.CharField(max_length=200)),
                ('employer_addr2', models.CharField(max_length=200)),
                ('employer_city', models.CharField(max_length=200)),
                ('employer_state', models.CharField(max_length=200)),
                ('employer_zip', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('account_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
        ),
        migrations.AddField(
            model_name='m2datafile',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.metro2event'),
        ),
        migrations.CreateModel(
            name='L1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_ind', models.CharField(max_length=200)),
                ('new_acc_num', models.CharField(max_length=200)),
                ('new_id_num', models.CharField(max_length=200)),
                ('account_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
        ),
        migrations.CreateModel(
            name='K4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spc_pmt_ind', models.CharField(max_length=200)),
                ('deferred_pmt_st_dt', models.DateField(null=True)),
                ('balloon_pmt_due_dt', models.DateField(null=True)),
                ('balloon_pmt_amt', models.IntegerField()),
                ('account_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
        ),
        migrations.CreateModel(
            name='K3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.CharField(max_length=200)),
                ('agency_acct_num', models.CharField(max_length=200)),
                ('min', models.CharField(max_length=200)),
                ('account_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
        ),
        migrations.CreateModel(
            name='K2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purch_sold_ind', models.CharField(max_length=200)),
                ('purch_sold_name', models.CharField(max_length=200)),
                ('account_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
        ),
        migrations.CreateModel(
            name='K1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_creditor_name', models.CharField(max_length=200)),
                ('creditor_classification', models.CharField(max_length=200)),
                ('account_activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
        ),
        migrations.CreateModel(
            name='J2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('gen_code', models.CharField(max_length=200)),
                ('ssn', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('ecoa', models.CharField(max_length=200)),
                ('cons_info_ind', models.CharField(max_length=200)),
                ('country_cd', models.CharField(max_length=200)),
                ('addr_line_1', models.CharField(max_length=200)),
                ('addr_line_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('addr_ind', models.CharField(max_length=200)),
                ('res_cd', models.CharField(max_length=200)),
                ('account_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='J1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('gen_code', models.CharField(max_length=200)),
                ('ssn', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('ecoa', models.CharField(max_length=200)),
                ('cons_info_ind', models.CharField(max_length=200)),
                ('account_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('gen_code', models.CharField(max_length=200)),
                ('ssn', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=200)),
                ('ecoa', models.CharField(max_length=200)),
                ('cons_info_ind', models.CharField(max_length=200)),
                ('country_cd', models.CharField(max_length=200)),
                ('addr_line_1', models.CharField(max_length=200)),
                ('addr_line_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('addr_ind', models.CharField(max_length=200)),
                ('res_cd', models.CharField(max_length=200)),
                ('activity_date', models.DateField()),
                ('cons_acct_num', models.CharField(max_length=200)),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.m2datafile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accountactivity',
            name='account_holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountholder'),
        ),
    ]
