# Generated by Django 4.2.20 on 2025-05-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivity',
            name='php1',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
