# Generated by Django 4.2.29 on 2026-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2datafile',
            name='collection',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
