# Generated by Django 4.2.9 on 2024-02-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k4',
            name='balloon_pmt_amt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unparseabledata',
            name='error_description',
            field=models.CharField(max_length=2000),
        ),
    ]
