# Generated by Django 4.2.20 on 2025-05-12 15:49

from django.db import migrations


def set_php1(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AccountActivity = apps.get_model("parse_m2", "AccountActivity")
    for a in AccountActivity.objects.all():
        a.php1 = a.php[0] if a.php else ""
        a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0002_accountactivity_php1'),
    ]

    operations = [
        migrations.RunPython(set_php1),
    ]
