# Generated by Django 4.2.20 on 2025-05-12 15:49

from django.db import migrations
from django.db.models.functions import Substr


def set_php1(apps, schema_editor):
    AccountActivity = apps.get_model("parse_m2", "AccountActivity")
    AccountActivity.objects.update(php1=Substr("php", 1, 1))


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0002_accountactivity_php1'),
    ]

    operations = [
        migrations.RunPython(set_php1),
    ]
