# Generated by Django 4.2.10 on 2024-02-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0002_unparseable_data_error_and_k4_optional_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountactivity',
            options={'verbose_name_plural': 'Account Activities'},
        ),
        migrations.AlterModelOptions(
            name='accountholder',
            options={'verbose_name_plural': 'Account Holders'},
        ),
        migrations.AlterModelOptions(
            name='j1',
            options={'verbose_name_plural': 'J1 Segment Associated Consumer - Same Address'},
        ),
        migrations.AlterModelOptions(
            name='j2',
            options={'verbose_name_plural': 'J2 Segment Associated Consumer - Different Address'},
        ),
        migrations.AlterModelOptions(
            name='k1',
            options={'verbose_name_plural': 'K1 Segment Original Creditor Name'},
        ),
        migrations.AlterModelOptions(
            name='k2',
            options={'verbose_name_plural': 'K2 Segment Purchased From/Sold To'},
        ),
        migrations.AlterModelOptions(
            name='k3',
            options={'verbose_name_plural': 'K3 Segment Mortgage Information'},
        ),
        migrations.AlterModelOptions(
            name='k4',
            options={'verbose_name_plural': 'K4 Segment Specialized Payment Information'},
        ),
        migrations.AlterModelOptions(
            name='l1',
            options={'verbose_name_plural': 'L1 Segment Account Number/Identification Number Change'},
        ),
        migrations.AlterModelOptions(
            name='m2datafile',
            options={'verbose_name_plural': 'Metro2 Data Files'},
        ),
        migrations.AlterModelOptions(
            name='metro2event',
            options={'verbose_name_plural': 'Metro2 Events'},
        ),
        migrations.AlterModelOptions(
            name='n1',
            options={'verbose_name_plural': 'N1 Segment Employment'},
        ),
        migrations.AlterModelOptions(
            name='unparseabledata',
            options={'verbose_name_plural': 'Unparseable Data'},
        ),
    ]
