# Generated by Django 4.2.10 on 2024-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0002_alter_accountactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unparseabledata',
            name='error_description',
            field=models.CharField(max_length=2000),
        ),
    ]
