# Generated by Django 5.2.17 on 2026-09-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0002_m2datafile_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro2event',
            name='total_tradelines',
            field=models.IntegerField(default=0),
        ),
    ]
