# Generated by Django 4.2.10 on 2024-02-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parse_m2', '0003_alter_accountactivity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro2event',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
