# Generated by Django 5.2.17 on 2026-09-28 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0003_metro2event_total_tradelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2datafile',
            name='previous_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parse_m2.m2datafile'),
        ),
    ]
