# Generated by Django 4.2.20 on 2025-06-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0003_set_php1'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountactivity',
            index=models.Index(fields=['activity_date'], name='parse_m2_ac_activit_3ed983_idx'),
        ),
    ]
