# Generated by Django 4.2.10 on 2024-02-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0003_unparseable_data_allow_longer_error_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k4',
            name='balloon_pmt_amt',
            field=models.IntegerField(null=True),
        ),
    ]
