# Generated by Django 4.2.10 on 2024-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0003_alter_accountactivity_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountactivity',
            index=models.Index(fields=['cons_acct_num'], name='parse_m2_ac_cons_ac_4b12fb_idx'),
        ),
    ]
