# Generated by Django 5.2.17 on 2026-10-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0004_m2datafile_previous_file'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountactivity',
            name='parse_m2_ac_cons_ac_4b12fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='accountactivity',
            name='parse_m2_ac_activit_3ed983_idx',
        ),
        migrations.AddIndex(
            model_name='accountactivity',
            index=models.Index(fields=['event_id', 'cons_acct_num'], name='parse_m2_ac_event_i_1d84ca_idx'),
        ),
        migrations.AddIndex(
            model_name='accountactivity',
            index=models.Index(fields=['event_id', 'activity_date'], name='parse_m2_ac_event_i_5ee20c_idx'),
        ),
    ]
