# Generated by Django 5.2.17 on 2026-10-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0005_remove_accountactivity_parse_m2_ac_cons_ac_4b12fb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro2event',
            name='prior_records_associated',
            field=models.IntegerField(default=0),
        ),
    ]
