# Generated by Django 4.2.10 on 2024-04-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0005_accountactivity_parse_m2_ac_cons_ac_4b12fb_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2datafile',
            name='error_message',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='m2datafile',
            name='parsing_status',
            field=models.CharField(default='Not started', max_length=200),
        ),
    ]
