# Generated by Django 4.2.11 on 2024-05-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0006_m2datafile_error_message_m2datafile_parsing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivity',
            name='id_num',
            field=models.CharField(default='', max_length=200),
        ),
    ]
