# Generated by Django 4.2.11 on 2024-04-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0006_m2datafile_error_message_m2datafile_parsing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivity',
            name='doai',
            field=models.DateField(null=True),
        ),
    ]
