# Generated by Django 4.2.11 on 2024-05-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0007_accountactivity_id_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro2event',
            name='eid_or_matter_num',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='metro2event',
            name='other_descriptor',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='metro2event',
            name='portfolio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
