# Generated by Django 4.2.11 on 2024-05-22 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parse_m2', '0008_metro2event_eid_or_matter_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metro2event',
            name='user_group',
        ),
        migrations.AddField(
            model_name='metro2event',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
