# Generated by Django 4.2.11 on 2024-05-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0009_remove_metro2event_user_group_metro2event_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro2event',
            name='directory',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
