# Generated by Django 4.2.11 on 2024-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0010_metro2event_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountactivity',
            name='doai',
            field=models.DateField(null=True),
        ),
    ]
