# Generated by Django 4.2.11 on 2024-06-12 17:00

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0010_metro2event_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='cons_info_ind_assoc',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='ecoa_assoc',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
