# Generated by Django 4.2.11 on 2024-06-17 17:02

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0011_alter_accountactivity_doai'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountholder',
            name='cons_info_ind_assoc',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='ecoa_assoc',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
