# Generated by Django 4.2.11 on 2024-06-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0012_accountholder_cons_info_ind_assoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro2event',
            name='date_range_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='metro2event',
            name='date_range_start',
            field=models.DateField(null=True),
        ),
    ]
