# Generated by Django 4.2.11 on 2024-07-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0013_metro2event_date_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivity',
            name='previous_values',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parse_m2.accountactivity'),
        ),
    ]
