# Generated by Django 4.2.11 on 2024-07-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0014_accountactivity_previous_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='m2datafile',
            name='parser_version',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
