# Generated by Django 4.2.15 on 2024-08-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0015_m2datafile_parser_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivity',
            name='event_id',
            field=models.IntegerField(default=-1),
        ),
    ]
