# Generated by Django 4.2.15 on 2024-08-16 16:15

from django.db import migrations


def populate_event_id(apps, schema_editor):
    Metro2Event = apps.get_model("parse_m2", "Metro2Event")
    AccountActivity = apps.get_model("parse_m2", "AccountActivity")

    for ev in Metro2Event.objects.all():
        print(f"Updating event {ev.id}: {ev.name}...")
        record_set = AccountActivity.objects.filter(account_holder__data_file__event=ev)
        record_set.update(event_id = ev.id)

class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0016_accountactivity_event_id'),
    ]

    operations = [
        migrations.RunPython(populate_event_id)
    ]
