# Generated by Django 4.2.15 on 2024-08-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse_m2', '0017_populate_event_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accountactivity',
            index=models.Index(condition=models.Q(('event_id__gt', 0)), fields=['event_id'], name='idx_event_id_when_present'),
        ),
    ]
