# Generated by Django 4.2.5 on 2023-11-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=200, unique=True)),
                ('hits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('field_values', models.JSONField()),
                ('record_id', models.CharField(max_length=24, unique=True)),
                ('acct_num', models.CharField(max_length=30)),
            ],
        ),
    ]
