# Generated by Django 4.2.17 on 2024-12-26 17:10

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parse_m2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorMetadata',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('fields_used', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('fields_display', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('crrg_reference', models.TextField(blank=True)),
                ('potential_harm', models.TextField(blank=True)),
                ('rationale', models.TextField(blank=True)),
                ('alternate_explanation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Evaluator Metadata',
            },
        ),
        migrations.CreateModel(
            name='EvaluatorResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.IntegerField()),
                ('accounts_affected', models.IntegerField(null=True)),
                ('inconsistency_start', models.DateField(null=True)),
                ('inconsistency_end', models.DateField(null=True)),
                ('evaluator_version', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate_m2.evaluatormetadata')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.metro2event')),
            ],
            options={
                'verbose_name_plural': 'Evaluator Result Summaries',
            },
        ),
        migrations.CreateModel(
            name='EvaluatorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('field_values', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('acct_num', models.CharField(max_length=30)),
                ('result_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate_m2.evaluatorresultsummary')),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse_m2.accountactivity')),
            ],
            options={
                'verbose_name_plural': 'Evaluator Results',
                'indexes': [models.Index(fields=['acct_num'], name='evaluate_m2_acct_nu_0c023e_idx')],
            },
        ),
    ]
