# Generated by Django 4.2.17 on 2025-01-03 14:57

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorresultsummary',
            name='sample_ids',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
