# Generated by Django 4.2.5 on 2023-12-20 22:13

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatormetadata',
            name='alternative_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='crrg_page',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='crrg_topics',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='fields_display',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='fields_used',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='ipl',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='pdf_page',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='risk_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='use_notes',
            field=models.TextField(blank=True),
        ),
    ]
