# Generated by Django 5.2.14 on 2026-07-08 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatormetadata',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='additional_notes_last_modified',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='interpret_fields_last_modified',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
