# Generated by Django 4.2.17 on 2025-01-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0002_evaluatorresultsummary_sample_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatorresult',
            name='field_values',
        ),
    ]
