# Generated by Django 4.2.9 on 2024-02-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0002_add_metadata_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluatormetadata',
            options={'verbose_name_plural': 'Evaluator Metadata'},
        ),
        migrations.AlterModelOptions(
            name='evaluatorresult',
            options={'verbose_name_plural': 'Evaluator Results'},
        ),
        migrations.AlterModelOptions(
            name='evaluatorresultsummary',
            options={'verbose_name_plural': 'Evaluator Result Summaries'},
        ),
    ]
