# Generated by Django 4.2.17 on 2025-01-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0002_evaluatorresultsummary_sample_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatormetadata',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
