# Generated by Django 4.2.17 on 2025-01-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0003_evaluatormetadata_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatorresult',
            name='field_values',
        ),
    ]
