# Generated by Django 5.2.14 on 2026-07-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0003_evaluatorresultmaterializedview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatorresultsummary',
            name='sample_ids',
        ),
        migrations.AddField(
            model_name='evaluatorresult',
            name='sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluatorresultsummary',
            name='accounts_affected',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='evaluatorresultsummary',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
