# Generated by Django 4.2.10 on 2024-03-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0004_eval_metadata_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evaluatorresult',
            index=models.Index(fields=['acct_num'], name='evaluate_m2_acct_nu_0c023e_idx'),
        ),
    ]
