# Generated by Django 5.2.14 on 2026-08-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0004_remove_evaluatorresultsummary_sample_ids_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluatorresultmaterializedview',
            options={'managed': False, 'verbose_name_plural': 'Evaluator Result Materialized View'},
        ),
    ]
