# Generated by Django 4.2.10 on 2024-04-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0005_evaluatorresult_evaluate_m2_acct_nu_0c023e_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluatormetadata',
            name='ipl',
        ),
        migrations.RemoveField(
            model_name='evaluatormetadata',
            name='name',
        ),
        migrations.RemoveField(
            model_name='evaluatormetadata',
            name='risk_level',
        ),
    ]
