# Generated by Django 4.2.10 on 2024-04-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0006_remove_evaluatormetadata_ipl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluatormetadata',
            old_name='alternative_explanation',
            new_name='alternate_explanation',
        ),
        migrations.RenameField(
            model_name='evaluatormetadata',
            old_name='use_notes',
            new_name='crrg_reference',
        ),
        migrations.RemoveField(
            model_name='evaluatormetadata',
            name='crrg_page',
        ),
        migrations.RemoveField(
            model_name='evaluatormetadata',
            name='crrg_topics',
        ),
        migrations.RemoveField(
            model_name='evaluatormetadata',
            name='pdf_page',
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='potential_harm',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluatormetadata',
            name='rationale',
            field=models.TextField(blank=True),
        ),
    ]
