# Generated by Django 4.2.11 on 2024-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0007_rename_alternative_explanation_evaluatormetadata_alternate_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorresultsummary',
            name='accounts_affected',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='evaluatorresultsummary',
            name='inconsistency_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='evaluatorresultsummary',
            name='inconsistency_start',
            field=models.DateField(null=True),
        ),
    ]
