# Generated by Django 4.2.11 on 2024-05-28 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0008_evaluatorresultsummary_accounts_affected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorresultsummary',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
