# Generated by Django 4.2.14 on 2024-07-30 15:44

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0009_evaluatorresultsummary_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluatorresult',
            name='field_values',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
