# Generated by Django 4.2.14 on 2024-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate_m2', '0010_alter_evaluatorresult_field_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorresultsummary',
            name='evaluator_version',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
